#!/usr/bin/env bash
#
# patch-android.sh — apply the native Android pieces that aren't expressed in JS,
# run in CI right after `npx cap add android` + `npx cap sync android`. The
# Android project is regenerated on every CI run (not committed, see ../.gitignore),
# so these edits must be scripted.
#
# Scope: AndroidManifest permissions for background audio + the media
# notification (FOREGROUND_SERVICE[_MEDIA_PLAYBACK], WAKE_LOCK, POST_NOTIFICATIONS;
# INTERNET is already in the Capacitor template).
#
# App icons are NOT handled here — they're generated by @capacitor/assets in a
# dedicated CI step (robust across the Capacitor template's legacy + adaptive
# icon layout, which a hand-rolled resize can't reliably target).
#
# Unlike iOS there is NO MainActivity edit: the system WebView drives the media
# notification, and prev/next/play/pause come from navigator.mediaSession (JS,
# src/api/mediaSession.ts). So no native ±10s-skip suppression is needed.
#
# Idempotent: re-running is a no-op. Fails loudly if the </manifest> anchor is
# missing so a Capacitor template change surfaces in the CI log.

set -euo pipefail

# Resolve paths relative to this script (mobile/scripts/) so it works regardless
# of the caller's CWD.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MOBILE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
ANDROID_DIR="$MOBILE_DIR/android"
APP_MAIN="$ANDROID_DIR/app/src/main"
MANIFEST="$APP_MAIN/AndroidManifest.xml"

echo "==> patch-android: manifest = $MANIFEST"

[ -f "$MANIFEST" ] || { echo "ERROR: AndroidManifest.xml not found at $MANIFEST"; exit 1; }

# ---------------------------------------------------------------------------
# AndroidManifest.xml -> background-audio + media-notification permissions
# Inserted before </manifest>. Guarded on FOREGROUND_SERVICE so re-runs and
# a template that already grants them are both no-ops.
# ---------------------------------------------------------------------------
if grep -q "android.permission.FOREGROUND_SERVICE\b" "$MANIFEST"; then
  echo "==> background-audio permissions already present, skipping"
else
  grep -q "</manifest>" "$MANIFEST" || { echo "ERROR: </manifest> anchor not found in $MANIFEST"; exit 1; }
  PERMS='    <!-- Latency: keep audio + the media notification alive in background -->\
    <uses-permission android:name="android.permission.WAKE_LOCK" />\
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />\
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE_MEDIA_PLAYBACK" />\
    <uses-permission android:name="android.permission.POST_NOTIFICATIONS" />\
'
  # Insert the permission block immediately before the closing </manifest> tag.
  sed -i "s#</manifest>#${PERMS}</manifest>#" "$MANIFEST"
  echo "==> background-audio permissions added"
fi

# ---------------------------------------------------------------------------
# Lock the app to portrait — rotation is unwanted here. Add screenOrientation to
# the MainActivity. Idempotent (guarded on the attribute already being present).
# ---------------------------------------------------------------------------
if grep -q 'android:screenOrientation' "$MANIFEST"; then
  echo "==> screenOrientation already set, skipping"
else
  grep -q 'android:name=".MainActivity"' "$MANIFEST" || { echo "ERROR: MainActivity anchor not found in $MANIFEST"; exit 1; }
  sed -i 's#android:name=".MainActivity"#android:screenOrientation="portrait"\n            android:name=".MainActivity"#' "$MANIFEST"
  echo "==> MainActivity locked to portrait"
fi

echo "==> patch-android: done"
echo "----- granted permissions -----"
grep "uses-permission" "$MANIFEST" || true
